### ISSUE TITLE
Does the current version of this work in Debian Stretch?

### ISSUE THREAD

**Issue by rynnon** [wyhasany/sample-service-script#9]
I've used this without problems in Debian Jessie, but I'm wondering if anything concerning this changed between Jessie and Stretch, and/or whether this was kept updated to reflect those changes.

**Comment by wyhasany** [comment]
After short investigation it looks like `/etc/rc.local` is [deprecated](https://stackoverflow.com/questions/44797694/where-is-rc-local-in-debian-9-debian-stretch). But if you make instructions from the link it will work correctly.
